# Generated by Django 3.0.7 on 2020-07-29 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questrite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionsDropouts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions_d', models.TextField()),
                ('answers_d', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionsGraduates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions_g', models.TextField()),
                ('answers_g', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionsSchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions_s', models.TextField()),
                ('answers_s', models.CharField(max_length=100)),
            ],
        ),
    ]
