# Generated by Django 3.0.7 on 2020-07-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questrite', '0003_auto_20200729_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswersDropouts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers_d', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AnswersGraduates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers_g', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AnswersSchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers_s', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='questionsdropouts',
            name='answers_d',
        ),
        migrations.RemoveField(
            model_name='questionsgraduates',
            name='answers_g',
        ),
        migrations.RemoveField(
            model_name='questionsschool',
            name='answers_s',
        ),
    ]
