# Generated by Django 3.0.7 on 2020-07-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questrite', '0004_auto_20200729_1618'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnswersDropouts',
        ),
        migrations.DeleteModel(
            name='AnswersGraduates',
        ),
        migrations.DeleteModel(
            name='AnswersP',
        ),
        migrations.DeleteModel(
            name='AnswersSchool',
        ),
        migrations.AddField(
            model_name='questionsdropouts',
            name='answers_d',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='questionsgraduates',
            name='answers_g',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='questionsp',
            name='answers',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='questionsschool',
            name='answers_s',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
